sudo: false
language: ruby
rvm:
- 2.2.2
cache: bundler
bundler_args: "--without development"
script: mkdir -p deploy/dataset-sync-wrapper && cp -r *.html *.js bower_components deploy/dataset-sync-wrapper/
after_success: if [ "$TRAVIS_BRANCH" == "production" ]; then bundle exec s3_website push --site deploy; fi
env:
  global:
  - secure: LDIIdeO68UG3IBvrqzPTjexSbo6yUvKxuLnIp3s2MG/XgW7fK//InMDAHmjFpBSaBEN0m/DQjHt25WUXB5bekNTPbcz4Bzubc9wFBJyBfjM88ja03gFZiY9r2F6yLb65NI4NCxt5KP1HA7J+tm9qPvl9PNJJo87cRP8di8/g1WI=
  - secure: PLlRxUIs9RrH9Dk9udfyYcqpTMS1e4qugWw0qMByin3SYibLE5JAECushXY35nbrdgE1pDpQg0b2JI+w60CEGfWWQ8feUkydF1STikD6tdBXEfwMiKqYiqH1/4d6tiH38U9e/9F4CDTx2ZiqH33gWoglLENRrcqOVKWY5+WZv/s=
