sudo: false
language: ruby
rvm:
- 2.2.2
cache: bundler
bundler_args: "--without development"
branches:
  only:
  - production
script: mkdir -p deploy/dataset-sync-wrapper && cp -r *.html *.js bower_components deploy/dataset-sync-wrapper/
after_success: bundle exec s3_website push --site deploy
env:
  global:
  - secure: JyXnozCwLHPXd5jR2TUgmLiBwJw1vRU4Ci0fcDcQWoYNGK4AV1vInUaKkQAMpqSM+OS5juDPbXcb2jZLHucfpUDrNLvSsujsFtKRjWMIcPT8ys1Y1xkp4smBcrGFc1ql8u1orBDb5hzz40dyg47MLoPK42+hdePHH/AYF/AKFrY=
  - secure: IMoEkkvGpyvG4n12tY50Hda/nQQ6dd+jA8Vj+LAu8RxW/nGRWtBhV/e3Pl+5kmetKUEj8Ev7wCT0S6yFUCLIeLCO/BDamj6u1C2UhyNT1uHNqqrlFztnPlrDzFWXKHdZtoRw/6/8lTvVPRDqnSLrnLn/S2QlJr/lOKHX/onInY8=
